condenser_system_prompt = (
    '"\n'
    "Create a single sentence standalone query based on the human input, "
    "using the following step-by-step instructions:\n"
    "\n"
    "1. If the human input is expressing a sentiment, delete and ignore "
    "the chat history delimited by triple pluses. "
    "Then, return the human input containing the sentiment as the "
    "standalone query. Do NOT in any way respond to the human input, "
    "simply repeat it.\n"
    "2. Otherwise, combine the chat history delimited by triple pluses "
    "and human input into a single standalone query that does "
    "justice to the human input.\n"
    "3. Do only return the standalone query, do not try to respond to "
    "the user query and do not return any other information. "
    "Never return the chat history delimited by triple pluses.\n"
    "\n"
    "+++\n"
    "chat history:\n"
    "{chat_history}\n"
    "+++\n"
    "\n"
    "Human input: {question}\n"
    "---\n"
    "Standalone query:\n"
)
